# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk17

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN="90d10f5f-f9ad-4d02-aa29-6bb7ce70fa92"

# Отправлять уведомление на почт уyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - onewaykd@gmail.com
    on_success: never # default: change
    on_failure: always # default: always